# This file tells Netlify how to build your Twig app

[build]
  # 1. Base Directory:
  # Tell Netlify to 'cd' into your 'twig-app' folder before running any commands.
  base = "twig-app"

  # 2. Build Command:
  # The *exact* steps to build everything, in order.
  command = "composer install --no-dev --optimize-autoloader && npm install && npm run build:css"

  # 3. Publish Directory:
  # The folder Netlify should serve to the public.
  publish = "twig-app"

[build.environment]
  # 4. Environment Versions:
  # Explicitly tell Netlify which tool versions to install.
  NODE_VERSION = "20"
  PHP_VERSION = "8.2"

